local keymap = vim.keymap

keymap.set("n", ";", ":", { desc = "CMD enter command mode", noremap = true })
keymap.set("n", "<C-d>", "<C-d>zz")
keymap.set("n", "<C-u>", "<C-u>zz")
keymap.set("n", "n", "nzzzv")
keymap.set("n", "N", "Nzzzv")
keymap.set("n", "J", "mzJ`z")
keymap.set("n", "Y", "yg$")
keymap.set("", "L", "$")
keymap.set("", "H", "^")
keymap.set("", "K", "%")
keymap.set("", "$", "<nop>")
keymap.set("", "^", "<nop>")
keymap.set("", "%", "<nop>")
keymap.set("n", "<tab>", "<cmd>bnext<CR>", { desc = "Next buffer" })
keymap.set("n", "<S-tab>", "<cmd>bprev<CR>", { desc = "Previous buffer" })
keymap.set("n", "<leader>x", "<cmd>bdelete<CR>", { desc = "Close buffer" })
keymap.set("x", "<leader>p", '"_dP', { desc = "Paste without yanking" })
keymap.set({"n", "v"}, "<leader>y", '"+y', { desc = "Yank to system clipboard" })
keymap.set({"n", "v"}, "<leader>d", '"_d', { desc = "Delete without yanking" })
keymap.set("n", "Q", "<nop>")
keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left" })
keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right" })
keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus down" })
keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus up" })

-- this will be handled by a plugin
-- keymap.set({"n", "v"}, "<leader>/", "gcc", { desc = "Toggle comment", noremap = false })

keymap.set("n", "<leader>k", ":lua require('nvim-tree.api').tree.toggle { find_file = true, focus = true }<CR>", { desc = "Toggle NvimTree", silent = true })
keymap.set("n", "<leader>?", ":lua require('which-key').show({ global = false })<CR>", { desc = "Show which-key mappings", silent = true })
