return {
  -- Snacks.nvim
  {
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    opts = {
      bigfile = { enabled = false },
      dashboard = { enabled = false },
      explorer = { enabled = false },
      indent = { enabled = false },
      input = { enabled = false },
      picker = { enabled = true },
      notifier = { enabled = false },
      quickfile = { enabled = false },
      scope = { enabled = false },
      scroll = { enabled = false },
      statuscolumn = { enabled = false },
      words = { enabled = false },
    },
    keys = {
      { "<leader>fp", function() require("snacks").picker.pick() end, desc = "Snacks: meta picker" },
      { "<leader>fr", function() require("snacks").picker.resume() end, desc = "Snacks: picker resume" },
      { "<leader>fb", function() require("snacks").picker.buffers() end, desc = "Snacks: buffers" },
      { "<leader>ff", function() require("snacks").picker.files() end, desc = "Snacks: files" },
      { "<leader>fc", function() require("snacks").picker.commands() end, desc = "Snacks: commands" },
      { "<leader>fd", function() require("snacks").picker.diagnostics() end, desc = "Snacks: diagnostics" },
      { "<leader>fD", function() require("snacks").picker.diagnostics_buffer() end, desc = "Snacks: diagnostics (buffer)" },
      { "<leader>fw", function() require("snacks").picker.grep() end, desc = "Snacks: grep" },
      { "<leader>gl", function() require("snacks").picker.git_log() end, desc = "Snacks: git log" },
      { "<leader>gd", function() require("snacks").picker.git_diff() end, desc = "Snacks: git diff" },
      { "<leader>gf", function() require("snacks").picker.git_files() end, desc = "Snacks: git files" },
      { "<leader>gb", function() require("snacks").picker.git_branches() end, desc = "Snacks: git branches" },
      { "<leader>lr", function() require("snacks").picker.lsp_references() end, desc = "Snacks: lsp references" },
      { "<leader>ls", function() require("snacks").picker.lsp_symbols() end, desc = "Snacks: lsp symbols" },
      { "<leader>lS", function() require("snacks").picker.lsp_workspace_symbols() end, desc = "Snacks: lsp workspace symbols" },
    },
  },
}
